### ISSUE TITLE
Problem in 4.3.3

### ISSUE THREAD

**Issue by mjencabh** [Panopto/moodle-tiny_panoptoltibutton#4]
Hello
when installing on our sandbox it hides all menu.
I tryied to go down a version but it still dosent help any thing.

I havnt set LTI up so its working, wich is why i assume it wants to hide the button, but then hides the menu.

**Comment by mjencabh** [comment]
I confirm after setting it up on production site, same issue.

**Comment by mjencabh** [comment]
No need, it is because of an cache In our nginx configuration.

Best regards
Michael

Sendt fra Outlook til iOS<https://aka.ms/o0ukef>
________________________________
Fra: Adis Hrnjica ***@***.***>
Sendt: Wednesday, April 17, 2024 3:57:54 PM
Til: Panopto/moodle-tiny_panoptoltibutton ***@***.***>
Cc: Michael Jensen (mjen.cb - Underviser - CB) ***@***.***>; Author ***@***.***>
Emne: Re: [Panopto/moodle-tiny_panoptoltibutton] Problem in 4.3.3 (Issue #4)


Hello,

Thank you for reporting this issue. We will track this internally and investigate.

Thanks,
Adis

**Comment by zeroAps** [comment]
Thank you for the response. I'll close this for now in that case.

Thanks,
Adis
